services:
   # Elasticsearch service
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - app_net
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  # Kibana service
  kibana:
    container_name: Kibana
    image: docker.elastic.co/kibana/kibana:8.17.2
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - app_net

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Pass12345"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes: 
      - sqlvolume:/var/opt/mssql
    networks:
      - app_net

  web.api:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: Web.API/Dockerfile
    container_name: contenedor-webapi
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - sqlserver
      - elasticsearch
    networks:
      - app_net
    restart: on-failure
  


networks:
    app_net:
        driver: bridge

volumes:
  sqlvolume:
  elasticsearch-data:
